# Covariance

In [3]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\PRASANNA\Downloads\study_marks.csv")
df

Study_Hours  Marks
0          2.9   27.0
1          5.8   61.0
2          4.7   45.0
3          4.0   38.0
4          1.8   19.0
5          1.8    8.0
6          1.3    4.0
7          5.3   50.0
8          4.0   35.0
9          4.5   47.0

In [4]:
df.cov()

Study_Hours       Marks
Study_Hours     2.481000   28.906667
Marks          28.906667  348.711111

In [5]:
df.corr()

Study_Hours    Marks
Study_Hours      1.00000  0.98277
Marks            0.98277  1.00000

In [10]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\PRASANNA\Downloads\temp_icecream_sales.csv")
df

Temperature  IceCream_Sales
0           20             200
1           22             220
2           24             250
3           26             270
4           28             300
5           30             320
6           32             350
7           34             370
8           36             400
9           38             420

In [11]:
df.cov()

Temperature  IceCream_Sales
Temperature       36.666667      455.555556
IceCream_Sales   455.555556     5666.666667

In [12]:
df.corr()

Temperature  IceCream_Sales
Temperature        1.000000        0.999406
IceCream_Sales     0.999406        1.000000

In [14]:
df.var()

Temperature         36.666667
IceCream_Sales    5666.666667
dtype: float64

In [18]:
data = {
    "rain": [30,32,29,35,33],
    "sales": [150,130,200,80,100]
}
df = pd.DataFrame(data)

In [19]:
df

rain  sales
0    30    150
1    32    130
2    29    200
3    35     80
4    33    100

In [20]:
df.cov()

rain   sales
rain     5.7  -107.0
sales -107.0  2170.0

In [21]:
df.corr()

rain     sales
rain   1.000000 -0.962092
sales -0.962092  1.000000

In [22]:
df.var()

rain        5.7
sales    2170.0
dtype: float64

In [23]:
data = {
    "speed": [40,60,80,100,120],
    "distance": [768,564,456,345,250]
}
df = pd.DataFrame(data)

In [24]:
df

speed  distance
0     40       768
1     60       564
2     80       456
3    100       345
4    120       250

In [25]:
df.cov()

speed  distance
speed     1000.0   -6275.0
distance -6275.0   40410.8

In [27]:
df.corr()

speed  distance
speed     1.000000 -0.987109
distance -0.987109  1.000000

# Normalization

In [45]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [46]:
s = pd.Series([1000,2000,3000,5000,9000])
s      

0    1000
1    2000
2    3000
3    5000
4    9000
dtype: int64

In [47]:
s

0    1000
1    2000
2    3000
3    5000
4    9000
dtype: int64

In [48]:
s.min()

1000

In [49]:
s.max()

9000

In [50]:
s_norm = (s-s.min()) / (s.max() - s.min())
print(s_norm)

0    0.000
1    0.125
2    0.250
3    0.500
4    1.000
dtype: float64


In [51]:
s_norm = MinMaxScaler().fit_transform(s.values.reshape(-1,1))
print(s_norm)

[[0.   ]
 [0.125]
 [0.25 ]
 [0.5  ]
 [1.   ]]


In [54]:
df = pd.DataFrame({
    "speed": [40,60,80,100,120],
    "distance": [768,564,456,345,250]
})
df

speed  distance
0     40       768
1     60       564
2     80       456
3    100       345
4    120       250

In [55]:
df.min()

speed        40
distance    250
dtype: int64

In [56]:
df.max()

speed       120
distance    768
dtype: int64

In [58]:
norm_data =  MinMaxScaler().fit_transform(df)
norm_data

array([[0.        , 1.        ],
       [0.25      , 0.60617761],
       [0.5       , 0.3976834 ],
       [0.75      , 0.18339768],
       [1.        , 0.        ]])

In [61]:
norm_df = pd.DataFrame(norm_data, columns=df.columns)
norm_df

speed  distance
0   0.00  1.000000
1   0.25  0.606178
2   0.50  0.397683
3   0.75  0.183398
4   1.00  0.000000

# Standardization

In [62]:
s = pd.Series([1000,2000,3000,5000,9000])
s      

0    1000
1    2000
2    3000
3    5000
4    9000
dtype: int64

In [63]:
s.mean()

np.float64(4000.0)

In [64]:
s.std()

3162.2776601683795

In [68]:
Z_Score=(s - s.mean())/s.std()
print(Z_Score)

0   -0.948683
1   -0.632456
2   -0.316228
3    0.316228
4    1.581139
dtype: float64


In [73]:
from sklearn.preprocessing import StandardScaler
Z_Score = StandardScaler().fit_transform(s.values.reshape(-1,1))
print(Z_Score)

[[-1.06066017]
 [-0.70710678]
 [-0.35355339]
 [ 0.35355339]
 [ 1.76776695]]


In [75]:
Z_Score=(s - s.mean())/s.std(ddof=0)
print(Z_Score)

0   -1.060660
1   -0.707107
2   -0.353553
3    0.353553
4    1.767767
dtype: float64


In [77]:
df = pd.DataFrame({
    "speed": [40,60,80,100,120],
    "distance": [768,564,456,345,250]
})
df

speed  distance
0     40       768
1     60       564
2     80       456
3    100       345
4    120       250

In [78]:
Z_Score = StandardScaler().fit_transform(df)
Z_Score_df = pd.DataFrame(Z_Score, columns=df.columns)
print(Z_Score_df)

      speed  distance
0 -1.414214  1.620675
1 -0.707107  0.486091
2  0.000000 -0.114571
3  0.707107 -0.731918
4  1.414214 -1.260278


In [79]:
Z_Score

array([[-1.41421356,  1.62067462],
       [-0.70710678,  0.48609115],
       [ 0.        , -0.11457068],
       [ 0.70710678, -0.73191757],
       [ 1.41421356, -1.26027752]])